pipeline {
    agent any
    tools {
        maven "maven-nodo-principal"
    }
    stages {
        stage('Build') {
            steps {
                dir ("practicas/maven-adderapp") {
                    sh 'mvn -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
    post {
        dir (‘practicas/maven-adderapp’) {
            archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
        }
    }
}